// src/projectsData.js
const projectsData = [
    { id: 1, title: 'Project 1',keys: ['java', 'python'], description: 'Description for project 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 2, title: 'Project 2',keys: ['java', 'python'], description: 'Description for project 2Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Java', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 3, title: 'Project 3',keys: ['java', 'python'], description: 'Description for project 3Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'ML', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 4, title: 'Project 4',keys: ['java', 'python'], description: 'Description for project 4Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 5, title: 'Project 5',keys: ['java', 'python'], description: 'Description for project 5Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 6, title: 'Project 6',keys: ['java', 'python'], description: 'Description for project 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 7, title: 'Project 7',keys: ['java', 'python'], description: 'Description for project 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 8, title: 'Project 8',keys: ['java', 'python'], description: 'Description for project 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 9, title: 'Project 9',keys: ['java', 'python'], description: 'Description for project 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    { id: 10, title: 'Project 10',keys: ['java', 'python'], description: 'Description for project 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum', category: 'Python', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1zOSlgbjfI8Au4o9Py4m_4Cipf6pbCWqXgoZzokqQffB7eLFBpjKlgqflVg&s' },
    // Add more projects as needed
  ];
  
  export default projectsData;
  